### ISSUE TITLE
CT center vs iso center

### ISSUE THREAD

**Issue by crcrewso** [pymedphys/pymedphys#1596] opened 2021-12-13 22:10 UTC
I'm in the middle of troubleshooting an issue, but I have one structure set where the ct center and the iso center are both non-zero. the structureset is offset by quite a bit and after some testing I've been able to prove to myself that the ct center value in the roi file isn't being used.

**Comment by Matthew-Jennings** [comment] 2021-12-18 07:25
Duplicate of #1597

**Closed by Matthew-Jennings** 2021-12-18 07:25 UTC
