### ISSUE TITLE
Interoperability between EGSnrc and PyMedPhys

### ISSUE THREAD

**Issue by mchamberland** [pymedphys/pymedphys#399] opened 2019-06-20 11:42 UTC
Let's open the discussion on whether EGSnrc itself can be included in the web app. I have no idea where to even start. I'll offer what expertise I have.

**Comment by SimonBiggs** [comment] 2019-06-20 18:53
Yup :) sounds awesome :)

**Comment by hdclark** [comment] 2019-06-21 04:26
From what I can tell there is no easy, direct path from Fortran to Webassembly.

It might be *possible* if [flang](https://github.com/flang-compiler/flang) compiler support aligns with the particular flavour of Fortran the egs Mortran system emits. According to [this](http://fortranwiki.org/fortran/show/Compilers) it looks like only Fortran 2008 is supported. Rather if Fortran 77 is emitted, which I suspect is the case, then it might be *possible* to instead rely on f2c to transform like: 

    Mortran --(egs)--> Fortran77 --(f2c)--> C --(clang/emscripten)--> Webassembly --(...)--> web app.

Gfortran offers more robust Fortran language support, but I don't recall every hearing about bytecode support. Actually I think the GCC developers intentionally resist because it can result in some types of license circumvention. But this may have changed when LLVM appeared.

If the above pathway is viable, a faithful port still might be impossible. There are serious limitations in Webassembly at the moment, especially around floating-point optimizations (which might be necessary) and memory management. Signalling NaNs, for example, will be difficult to provide reliably. This will almost certainly be a very bumpy road.

**Comment by hdclark** [comment] 2019-06-21 04:34
Pinging @darcymason. He had some ideas when we were chatting about this on the 19th.

**Comment by SimonBiggs** [comment] 2019-06-21 05:05
Here are some related issues that might be able to help with ideas:

https://github.com/iodide-project/pyodide/issues/184
https://github.com/emscripten-core/emscripten/issues/998

**Comment by SimonBiggs** [comment] 2019-06-21 05:07
And here is the pr that did it:
https://github.com/iodide-project/pyodide/pull/211

**Comment by SimonBiggs** [comment] 2019-06-21 05:11
Some continued improvement is also going on at:

https://github.com/iodide-project/pyodide/pull/473

**Comment by SimonBiggs** [comment] 2019-06-21 06:15
@rtownson, this is where we'll be tracking EGSnrc to the browser efforts for a bit. See how we go ay.

**Comment by SimonBiggs** [comment] 2019-06-21 06:21
It does look like EGSnrc's mortran does emit f77:

https://github.com/nrc-cnrc/EGSnrc/blob/00b70e1e0289bd21b1bfbd28773b07520d267fb8/HEN_HOUSE/mortran3/check77.mortran#L41

**Comment by darcymason** [comment] 2019-06-21 16:36
> Pinging @darcymason. He had some ideas when we were chatting about this on the 19th.

I just had some theories, even assumptions,  I would say ... that since scipy has fortran libraries that there shouldn't be any fundamental limitations to mortran->fortran->...->webassembly working.  @SimonBiggs last comment seems hopeful in that regard.  In any case, you guys are deeper into this than me.  Watching with interest...

**Comment by crcrewso** [comment] 2020-06-08 15:20
The EGSnrc team is motivated to remove Mortran from the code base entirely for a few reasons. I had proposed replacing Mortran with a mix of Make and Python (where it makes sense). A proposed alternative would be rewriting the entirety of EGSnrc in rust. 

If people feel like contributing down these roads for EGSnrc that might be more helpful than keeping the legacy anchor that is mortran around.

**Comment by SimonBiggs** [comment] 2020-06-08 19:48
Oh wow, rewriting egs in rust. That is a very promising (and ambitious)
option. (It would also give webassembly for free...)

How many are interested in undergoing such an effort?

**Comment by SimonBiggs** [comment] 2020-06-08 19:51
...a big downside of course is one looses the rich verified history that egs has. I know personally I would much rather run my simulations on a tried and true code base.

...see, even when one uses scipy, we are still using Fortran. There is value on using old code bases, ones that have a deep and long history of being verified.

**Comment by crcrewso** [comment] 2020-06-08 19:52
True, very true, and it's a deep conversation to be had. If there was 2 years funding for such a project I'd take it on.

**Comment by SimonBiggs** [comment] 2020-06-08 19:58
Either way, it should be possible to distribute the current egs as Python wheels. And if that is done, there are already huge usability wins for the community. At the end of the day, if someone removes mortran, or rewrites it into rust, it still doesn't remove the need in the community for an easy to install python wheel package for egs. And to create that package one need only set up a compile CI for each OS. ... Big wins with small effort :) it is always great if a big project is full of really small ones that can be successful in their own right.

**Comment by ftessier** [comment] 2020-06-08 21:29
Yes we have been discussing an EGSnrc rewrite over the last year (well the last 10 years really...). For the history buffs there is a revealing quote in of the EGS4 files: _"And yes, Mortran MUST DIE but we have to put something as powerful in its place. Any volunteers?"_ That was in... 1991!! I reckon the call to action stands, almost 30 years later.

**Comment by ftessier** [comment] 2020-06-08 21:33
We have been looking into rewriting EGSnrc in C++ and also in Rust, and @mxxo is looking into that already. Any comments and suggestions welcome, technical or philosophical! Once we embark on this in earnest, we will announce it here and create a project branch where everyone will be welcome to contribute.

**Comment by SimonBiggs** [comment] 2020-06-08 21:49
I am quite keen to put my +1 vote next to choosing Rust over C++. I would also certainly be interested in lending a hand.

**Comment by ftessier** [comment] 2020-06-08 21:53
@SimonBiggs you are right, there is a lot of value in a vetted code. But the way the code is designed in rigid (global variables, monolithic code, fortran77 backend, etc.) _and_ fragile (for much the same reasons) in terms of development. Most of the vetting value resides in the core physics routines, and any new implementation of these can be vetted by brute force against the the legacy code as a reference. I think it is worth as shot! My top priorities would be:
- design data structures for particles, interactions, variance reduction and scoring that are 1) modular, 2) efficient, and 3) extensible.
- rewrite core physics functions as interaction traits of particle objects, with thorough fuzzy testing.
- consider variance reduction at the outset, rather than as an afterthought; perhaps vr as traits?
- similarly for scoring, again perhaps implemented as traits on particles and interactions

**Comment by ftessier** [comment] 2020-06-08 22:03
The task may seem daunting (it did to me until a couple years ago), but in reality the radiation transport problem EGSnrc is solving is conceptually simple **once the core physics and transport mechanics is resolved** (it is, thanks 🙏 to its authors!). In the end, it is _just_ a collection of particle objects with a few variables (r, u, E) that scatter (and create secondaries of course) via a relatively small set of functions. A _lot_ of the EGSnrc code has to do with arcane methods for input, output, and general data processing, much of which can be done much more easily today (especially if standard libraries are invoked, for example, although we want to limit external dependencies).

**Comment by ftessier** [comment] 2020-06-08 22:04
@SimonBiggs recorded your Rust vote. it is not an easy sell (I am still not 100% sold on this choice myself yet!)

**Comment by SimonBiggs** [comment] 2020-06-08 22:12
Also, if we truly are still in the brainstorming stage, can I extend horizons a little. If the choice of C++/Rust is for speed... don't discount Python (sounds crazy I know), but there are numerical libraries built to be able to be compiled to GPUs:

This one for example is built by DeepMind + Google with Machine Learning in mind:

* https://github.com/google/jax

They are certainly aiming for speed, and they achieve it in both development time and run time...

If all options are on the table, personally, I would prefer to redact my Rust vote and instead vote for a combination that leverages where a huge amount of computation speed up research + resources are currently being focused.

**Comment by hdclark** [comment] 2020-06-08 22:13
@ftessier +1 for (modern) C++. Rust is interesting and exciting, but the long term is hard to predict. C++ will definitely be around for at least a few more decades.

**Comment by SimonBiggs** [comment] 2020-06-08 22:15
@ftessier if I had a choice between relying on my vote or @hdclark's, I would recommend deferring to @hdclark in these matters :).

**Comment by ftessier** [comment] 2020-06-08 23:09
@hdclark this is why we are hesitant to go "full Rust", and will for the moment try it out with actual code (philosophical discussions can only get you so far...). I have been watching the Rust project since it became more serious in 2018, and I have to say I am enthralled by their governance, their commitment to code efficiency and to long term stability (horizon of 40 years). The core mission of Rust to make programming memory safe (and thread safe, by the same token) is really appealing. I would not bet on C++ being around (meaning mainstream) for decades, when there is such effervescence today around functional programming, safer programming, and as web applications have already overtaken the software industry. It is rapidly becoming the dinosaur in the room. I am not against C++ on principle though, I mean we are still using Mortran 😂

**Comment by ftessier** [comment] 2020-06-08 23:34
@SimonBiggs I am indeed not considering Python for the EGSnrc backend, perhaps naively. I will look at jax, I was not aware of such a project! I love python for all my scripting needs, but my understanding of its performance for numerical computation is limited to the general idea that as an interpreted language it _must_ be order(s) of magnitude slower than C. I am not at this point ready to commit to the effort to rewrite core EGSnrc routines in python, but I sure would like to see an actual comparison! 😄 No worries about your vote redaction; I find this discussion stimulating, keep the ideas and opinions coming. 👍

**Comment by hdclark** [comment] 2020-06-08 23:34
@ftessier Sounds like a reasoned approach. I predict C++ will be around for a while because the proposals since C++11 have gratuitously stolen useful ideas from Python, Haskell, and even ... Rust. Many big-ticket projects (e.g., LLVM, Chromium, V8, even Zircon) are using C++.

That being said, if the EGSnrc bikeshed gets painted a Rusty colour I will be happy.

**Comment by SimonBiggs** [comment] 2020-06-09 00:55
@ftessier the built in parallelisation of the random number generation is quite interesting:

https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html

**Comment by ftessier** [comment] 2020-06-09 03:10
Indeed, can't say I get it, but I think I get the idea. In EGSnrc of course, it is all pleasingly parallel (independent threads really), so we can just provide different seeds to each thread and off we go 😃 . Aaah the Mersenne Twister, my favorite RNG for "ever"; but upon looking up modern RNGs recently (lead there, you guessed it, from the [Rust Rand Book](https://rust-random.github.io/book/), I have taken a liking  [xoshiro generators](http://prng.di.unimi.it/), and I am looking forward to implementing `xoshiro256++` in EGSnrc! I was surprised to read on there that MT19937 fails the LinearComp test from BigCrush!

**Comment by ftessier** [comment] 2020-06-09 03:15
There is an ongoing discussion about the short term solution for the EGSnrc default rng in [issue 292](https://github.com/nrc-cnrc/EGSnrc/pull/292) if you feel like jumping in.

**Comment by SimonBiggs** [comment] 2020-06-09 03:31
Not sure if this applies to EGS RNG initialisation, but it seems that those seeds used across each thread must be carefully initialised according to the following:

> We demonstrate that a majority of modern random number generators, such as the newest version of rand.c, ranlux, and combined multiple recursive generators, have some manifest correlations in their outputs if the initial state is filled up using another linear recurrence with similar modulus. Among 58 available generators in the GNU scientific library, 40 show such defects. This is not because of the recursion, but because of carelessly chosen initialization schemes in the implementations. A good initialization scheme eliminates this phenomenon.

-- https://dl.acm.org/doi/10.1145/1276927.1276928

**Comment by ftessier** [comment] 2020-06-09 04:24
Wow, thanks for that paper reference, will read for sure, it is relevant to our current discussion of turning to ranlux as the default! (ranmar is reported as showing no affine transient, but ranlux does!). In Monte Carlo for radiation transport, we are often saved from bad rngs because the random numbers from the rng sequence are used for _all sorts of things_, for example the number of random numbers used in a given particle shower itself depends on the shower (on previous random numbers). But I'd rather get it right if possible.

**Comment by mchamberland** [comment] 2020-06-09 13:20
@SimonBiggs The discussion has completely veered off, but I'm interested in bundling EGSnrc into a Python wheel. No idea what it entails or if it's even achievable! Also, I will need to work on this outside of my regular working hours since I have no protected research time yet and we're down a physicist in the clinic lately.

**Comment by ftessier** [comment] 2020-06-09 13:53
Yes, sorry for the veering off, thanks for bringing this back on topic. For a while I thought I was on an EGSnrc repo thread. 😄

**Comment by SimonBiggs** [comment] 2020-08-16 21:41
> but in reality the radiation transport problem EGSnrc is solving is conceptually simple **once the core physics and transport mechanics is resolved** (it is, thanks 🙏 to its authors!).

@ftessier could you point me in the direction of the files that contain this core physics and transport logic, I personally know essentially zero fortran/mortran. I'm hoping to just begin to attempt to read through these files, as a recreational thing for now.

**Comment by rtownson** [comment] 2020-08-16 21:53
All of the core physics is indeed in HEN_HOUSE/src, in fact pretty much entirely within [HEN_HOUSE/src/egsnrc.mortran](https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/src/egsnrc.mortran). The part of transport mechanics that's not there is the geometry modelling - each application handles the geometries on its own (or for egs++ apps they all share the same [geometry classes](https://github.com/nrc-cnrc/EGSnrc/tree/master/HEN_HOUSE/egs%2B%2B/geometry)).

**Comment by SimonBiggs** [comment] 2020-08-16 21:55
Awesome, thanks @rtownson :)

**Comment by SimonBiggs** [comment] 2020-11-07 20:51
Hi @ftessier,

A python Monte Carlo statics library has been swapping out its backend for JAX recently. Their benefits seems to be speed just a little bit slower on a CPU when compared to C, but without any maintenance burden also being able to run the code on TPUs and GPUs with massive speed benefits.

Their blog post announcement is over at:

https://pymc-devs.medium.com/the-future-of-pymc3-or-theano-is-dead-long-live-theano-d8005f8a0e9b

I think a JAX based EGSnrc would be easy to maintain and potentially an order of magnitude (or two) faster that a CPU locked codebase.

**Comment by ftessier** [comment] 2020-11-10 14:48
Thanks for the head up on this @SimonBiggs, this is a possibility I had not considered. I had thought about a simulation interface in python with a C (and Mortran!) backend as a possible step forward. Reading a bit about JAX feeds those thoughts, to say the least! In the past year I have been eyeing Rust however....

**Comment by SimonBiggs** [comment] 2020-11-10 14:56
> In the past year I have been eyeing Rust however....

The fact that most articles in the following search are old and unofficial makes me think Rust might not be the best way to go if speed is the ultimate aim:

https://www.google.com/search?q=compiling+rust+to+GPU&oq=compiling+rust+to+GPU

...at the end of the day I'd imagine you'd want to be able to run the software on something like the following:

https://lambdalabs.com/gpu-workstations/vector

I think any re-write must make running on the GPU a first class citizen. And JAX comes with all of the power of XLA compilation (https://www.tensorflow.org/xla).

**Comment by ftessier** [comment] 2020-11-10 15:01
Point taken, and we certainly ought to think about running on GPUs or TPUs, especially if it comes at "zero" cost, so to speak, and if the source code remains general, i.e., it does not become tied to any particular hardware-of-the-day.

**Comment by SimonBiggs** [comment] 2020-11-10 15:04
> Point taken, and we certainly ought to think about running on GPUs or TPUs, especially if it comes at "zero" cost, so to speak, and if the source code remains general, i.e., it does not become tied to any particular hardware-of-the-day.

Yup, since JAX code is essentially numpy syntax it is exceptionally readable, maintainable, and the numpy syntax is sticking around for the long haul.

**Comment by SimonBiggs** [comment] 2020-12-29 01:30
@ftessier, to add another Monte Carlo library now also taking this approach this following library by Uber (https://pyro.ai/#about) that undergoes Hamiltonian Monte Carlo that is now rewriting its backend in numpy/JAX:

https://github.com/pyro-ppl/numpyro

...the more I read into it, it seems like this is most certainly a brilliant path/direction for EGSnrc to follow in...

**Comment by ftessier** [comment] 2020-12-29 14:52
Thanks for the update @SimonBiggs. I am looking at JAX (and XLA) documentation again, and the two parts of EGSnrc that in my mind could benefit from this are geometry operations (linear algebra) and simultaneous particle transport (_à la_ STOPS in vmc++). In order to play with this, we need a rudimentary port of radiation transport into python; anyone? I will add this to our list of potential EGSnrc-related projects!

**Comment by SimonBiggs** [comment] 2020-12-29 23:42
> In order to play with this, we need a rudimentary port of radiation transport into python; anyone?

Would you be able to point out a minimum viable set of functions within the Fortran source that would be a good starting place to port? ...ideally it'd also be awesome to be able to decoupled the random number generation, that way, the same random number sequence could be passed to both the Fortran version and the Python ported version and that can be used to verify that the port produces the same results as the Fortran reference...

**Comment by darcymason** [comment] 2020-12-30 00:47
> we need a rudimentary port of radiation transport into python; anyone?

I had a quick look at this - if the starting point is Fortran rather than Mortran, it looks like something like [transpyle](https://github.com/mbdevpl/transpyle) may be able to do some of the transpiling work.  I think it would be necessary given the ultimate scale of the conversion.  Or perhaps someone else knows a different tool - that one is the best I could find.

If you could post the Fortran (as per @SimonBiggs request above) I'd be willing to at least start looking at whether that can do some basic translation of flow structures, statements etc.

**Comment by SimonBiggs** [comment] 2020-12-30 00:55
> Or perhaps someone else knows a different tool

If one wants to be able to call the EGSnrc code within Python I've had some success with NumPy's f2py (https://numpy.org/doc/stable/f2py/) over in the following PR:

https://github.com/nrc-cnrc/EGSnrc/pull/627

However, I struggled with being able to wrap the EGSnrc in a decoupled manner into modular pieces that I could then wrap up.

**Comment by ftessier** [comment] 2020-12-30 01:03
Ideally the RNG would indeed be independent and reproducible, however in practice this is going to be difficult with different language and compilers! I predict we will have to resort to brute force (fuzzy) testing of the functions instead, but that does not worry me.

The **easiest** to port would be the geometry library, but the most **meaningful** would be the physics engine. Porting EGSnrc is a sizeable project, and for the purpose of testing a JAX implementation, for example, I would suggest a simpler Monte Carlo transport code, as a proof of principle. What I mean is that the EGSnrc code has developed its own intricacies (and idiosyncrasies!) over time. It would probably take more time than it is worth to _port_ all of it at this stage for the sake of investigating whether JAX has efficiency advantages (or not). The key routine to port though is `ELECTR` for electron transport. This is the most costly function, and the defining one in terms of setting EGSnrc apart from other codes in terms of accuracy and efficiency. On the geometry side, one could resort to a simple one for testing. If the physics with JAX can be made to run near on par with the Fortran backend is sufficient case (and hope) to look at porting the geometry library; but not necessarily the other way around.

The difficulty in porting (having tried a few ports myself, mostly for fun :-)) is not rewriting the functions; that's mostly straight math operations. The contortions appear because of the data structures implemented as a long list of common blocks. They are well-organized (kudos to the original authors), but it requires some deciphering. I would be willing to help bootstrap this, of course!

Again, the issue is to not waste a good few month's time rewriting the code, and _then_ find out it does not pan out at all. Transpilation at the outset as @darcymason suggested might be an early investigative option (the starting point can be Fortran, as Mortran just output a Fortran file). 

I would suggest working in stages, from simpler building blocks, even _synthetic_ ones. For example, first compare RNG speed. Then, load a `STACK` of particles (array of particles, or in the case of EGSnrc multiple arrays of particle properties such as position, direction, energy, etc.) and performing "random" operations on them (updating particle properties like in an interaction). If you can get JAX to do this near on par with a C implementation (as a Fortran surrogate), then we can move to the next stage, e.g., update the properties depending on some external table that depends on energy and position (reminiscent of sampling the cross-section), and so on. That is, building a case at every stage for the efficiency of the new implementation. It would be much quicker to code this in both C and Py/JAX then to convert the whole thing; at worse you would catch a no-go early, and at best you would identify optimal data and coding strategies as you go!

I anyone tries this, please keep in touch, I would be very interested to witness progress, and eventually contribute. If this has traction here, don't hesitate to start a [Discussion](https://github.com/nrc-cnrc/EGSnrc/discussions) on `nrc-cnrc/EGsnrc` about it!

**Comment by darcymason** [comment] 2020-12-30 03:30
> If one wants to be able to call the EGSnrc code within Python I've had some success with NumPy's f2py

I used that too (many many years ago) - it certainly might be helpful for pasting together Python code to parts that haven't been converted.

> The contortions appear because of the data structures implemented as a long list of common blocks.

I noticed that in my quick review too - a central question would be whether to continue to use globals, or pass data classes into subroutines.  The latter is certainly better practice, but would make the code transpilation more complicated - another reason why a programmable tool is useful.  The transpyre library uses XML to store the intermediate abstract syntax tree - I'm not a huge fan of XML in general, but in this case it might make customizing code conversion much more doable. 

> I would suggest working in stages, from simpler building blocks, even _synthetic_ ones. For example, first compare RNG speed. Then, load a `STACK` of particles (array of particles, or in the case of EGSnrc multiple arrays of particle properties such as position, direction, energy, etc.) and performing "random" operations on them (updating particle properties like in an interaction). If you can get JAX to do this near on par with a C implementation (as a Fortran surrogate)

Sounds like a good idea.  Probably makes sense to look into that before any transpiler effort like I mentioned.  Those kinds of tests are outside my abilities, but the transpilation does intrigue me and I will help there is I can.  I might take a look at `ELECTR` - looks like ~700 lines of code with lots of comments - some basic regex search-replace plus hand edits after might not be too bad.

**Comment by SimonBiggs** [comment] 2020-12-30 05:00
> Then, load a `STACK` of particles (array of particles, or in the case of EGSnrc multiple arrays of particle properties such as position, direction, energy, etc.) and performing "random" operations on them (updating particle properties like in an interaction). If you can get JAX to do this near on par with a C implementation (as a Fortran surrogate), then we can move to the next stage

In the following notebook on Google's colab infrastructure (for reproducible hardware comparisons) I set up a million particles with position, direction, and energy, and then I iterated on them with random normal numbers. 10 iterations took ~1.2 seconds when CPU bound, 10 iterations took ~14 ms when running on the GPU:

https://colab.research.google.com/drive/1QZKnByThJrq9NhgBbFb8Nx6cPybFVWZJ?usp=sharing

Given online benchmarks show that numpy on the CPU is on par with C in terms of speed:

https://stackoverflow.com/a/7614252/3912576

It seems like, for the hardware available on Google's colaboratory, a speed up of about 2 orders of magnitude might be expected.

**Comment by SimonBiggs** [comment] 2020-12-30 05:24
> update the properties depending on some external table that depends on energy and position (reminiscent of sampling the cross-section)

May as well use an actual table... is there a table (for example https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/data/eii_penelope.data) that you would recommend as being most relevant?

**Comment by SimonBiggs** [comment] 2020-12-30 05:25
@darcymason 

> but the transpilation does intrigue me and I will help there is I can. I might take a look at `ELECTR` - looks like ~700 lines of code with lots of comments - some basic regex search-replace plus hand edits after might not be too bad.

I think having that transpilation would be amazing and it would be a good way to divide and conquer this.

**Comment by ftessier** [comment] 2020-12-31 14:50
Ok, this is at least interesting then! I have run your python script locally (with `jaxlib` and `jax`, but no GPU); using a poor man's timer (wall time, `time.time()`), I get **1000 ms per run.** I have then coded the equivalent in C++ (with the same Mersenne Twister random number generator and weak timer) compiles with optimization `-O3` and got:
```
duration = 819 milliseconds
duration = 795 milliseconds
duration = 779 milliseconds
duration = 788 milliseconds
duration = 762 milliseconds
duration = 782 milliseconds
duration = 791 milliseconds
duration = 760 milliseconds
duration = 787 milliseconds
duration = 773 milliseconds
```

For the record, here is the code I used:
```c++
// compile with: g++ -std=c++17 -pedantic -Wall -O3 -Wextra particles.cc

// includes
#include <iostream>
#include <vector>
#include <chrono>
#include <random>

// defines
#define NUM_PARTICLES 1000000
#define ITERATIONS 10
#define RUNS 10

// main
int main () {

    // positions
    std::vector<double> x(NUM_PARTICLES, 0.0);
    std::vector<double> y(NUM_PARTICLES, 0.0);
    std::vector<double> z(NUM_PARTICLES, 0.0);

    // directions
    std::vector<double> u(NUM_PARTICLES, 0.0);
    std::vector<double> v(NUM_PARTICLES, 0.0);
    std::vector<double> w(NUM_PARTICLES, 0.0);

    // energies
    std::vector<double> E(NUM_PARTICLES, 0.0);

    // random number generator
    std::mt19937 generator(1);
    std::uniform_real_distribution<double> sample(-1.0, 1.0);

    // update particle arrays a number of times
    for (int run=0; run<RUNS; run++) {

        // poor man's timere
        auto start = std::chrono::high_resolution_clock::now();

        // update particle arrays
        for (int i=0; i<ITERATIONS; i++) {
            for (int n=0; n<NUM_PARTICLES; n++) {
                x[n] += sample(generator);
                y[n] += sample(generator);
                z[n] += sample(generator);
                u[n] += sample(generator);
                v[n] += sample(generator);
                w[n] += sample(generator);
                E[n] += sample(generator);
            }
        }

        // report duration
        auto stop = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(stop-start);
        std::cout << "duration = " << duration.count() << " milliseconds" << std::endl;
    }

    return EXIT_SUCCESS;
}
```

So Jax/Numpy is not bad! I will try to run this locally on the GPU with `@jit`. **I am opening a discussion in `nrc-cnrc/EGSnrc` about this** to discuss further.

**Comment by darcymason** [comment] 2020-12-31 15:53
And I've transpiled in a rough way probably about 70% of ELECTR (from Mortran, not Fortran`*`) ... using a python script with regular-expression search/replace to do the simple transforms.  Not too bad so far because the syntax is actually not too different, math expressions, etc. mostly unchanged, and the original is mostly already indented Python-style.  One tricky part is the common blocks, as mentioned, although I think I have an idea for that, at least to get to a testable level.  Some other hurdles remain, like `goto` logic.  It will still require a fair bit of hand-tuning, but I'm trying to do as much as possible in a script that could be adapted to future work, if it comes.  I don't know if we can get ELECTR completely working on its own, though, so may have to choose a subset or very restricted test conditions, likely with mock functions for various calls out.

`*` I realized that Mortran may be a better source language choice due to all the adjustable parameters / callback functions etc.  Due to the pervasive macro use, the code would be much less understandable from Fortran (e.g. named constants just become a number).  Perhaps there might be a path later of changing the macros to named constants and subroutines, and similar changes to make Fortran->Python transpiled code more understandable.  For now I'm just targeting the one ELECTR subroutine and enough to support it to get something running.

> **I am opening a discussion in `nrc-cnrc/EGSnrc` about this** to discuss further.

I'll post [over there](https://github.com/nrc-cnrc/EGSnrc/discussions/658) when I've got things developed a little further.

**Comment by ftessier** [comment] 2020-12-31 15:59
Thanks @darcymason, nice to know you can transpile at this level already!! In my mind, transpilation would be extremely useful to convince ourselves that acceptable performance can be achieved with a python backend. For the actual implementation, I would root to rewrite from scratch (perhaps with some inspiration from the transpiles code), to actually _get away_ from the somewhat convoluted and "fragile" original code.

**Comment by crcrewso** [comment] 2020-12-31 16:07
@ftessier I have the resources to be able to run a number of tests against both EGSnrc and the appropriate python replacement on the whole system level. Additionally I would be happy to do some unit testing on the python code. I would, however, need to a library of input files for testing. 

I've always been afraid of doing an implementation of EGSnrc myself because of how hard it is to unit test the original code base.

**Comment by darcymason** [comment] 2020-12-31 16:08
> For the actual implementation, I would root to rewrite from scratch (perhaps with some inspiration from the transpiles code), to actually _get away_ from the somewhat convoluted and "fragile" original code.

Agreed - the transpiled code I'm getting so far is built for testing only; starting from scratch one could definitely make it more pythonic and take advantage of arrays, generators, etc. for improved readability, maintainability and speed.

**Comment by ftessier** [comment] 2020-12-31 16:22
> @ftessier I have the resources to be able to run a number of tests against both EGSnrc and the appropriate python replacement on the whole system level. Additionally I would be happy to do some unit testing on the python code. I would, however, need to a library of input files for testing.
> 
> I've always been afraid of doing an implementation of EGSnrc myself because of how hard it is to unit test the original code base.

@crcrewso Thanks for the enthusiasm and the offer to help! Indeed, unit testing the original code is not a path I want to embark on (and loose myself in). For the back end, when it comes to testing the physics we can probably get away with fuzzy testing the hell out of every functions (e.g., compton, electr, brems, etc.), since these are mostly math operations, with well-defined inputs and outputs (except for the darn commons). Eventually, we can also test the geometry in this way (easier, since egs++ is already well packaged in objects with a _well-defined-ish_ API). One more difficult difficult part to verify is `HATCH` to ensure that the data files are read in correctly and the simulation set up as expected; but there are not too many files. Finally, the convoluted (yet thankfully extremely efficient!) logic in routines such as electron is a significant hurdle towards verification, as anyone that has played with modifying `ELECTR` can attest.

At any rate, we have some way to go to test efficiency with toy models, before embarking on this outright. And I am still eyeing Rust, in other news. 😉 

Please don't hesitate to comment further on the related `nrc-cnrc/EGSnrc` [Discussion](https://github.com/nrc-cnrc/EGSnrc/discussions/658). I fell like we highjacked @mchamberland original discussion (sorry Marc!) 😄

**Comment by mchamberland** [comment] 2020-12-31 18:32
@ftessier no worries. I’m glad this has picked up some steam. I’ll be happy to help testing!

**Comment by SimonBiggs** [comment] 2020-12-31 22:25
> And I've transpiled in a rough way probably about 70% of ELECTR (from Mortran, not Fortran*) ... using a python script with regular-expression search/replace to do the simple transforms.

> (perhaps with some inspiration from the transpiles code)

> Agreed - the transpiled code I'm getting so far is built for testing only;

@darcymason That is awesome. Would you be able to share the partially transpiled code? I think it'd significantly help me understand what's going on :slightly_smiling_face:.

**Comment by darcymason** [comment] 2021-01-01 00:30
> Would you be able to share the partially transpiled code?

Sure, I'll work on posting it up - its still a hot mess, though, so I'll add an issue there to explain where I think the next steps are going.  I think I see a path through to the end, but haven't hit all corners yet.

> I think it'd significantly help me understand what's going on 🙂.

And another set of eyes would probably do the same for me :smile:

**Comment by darcymason** [comment] 2021-01-01 01:14
WIP now available at darcymason/egsnrc2py.

**Comment by SimonBiggs** [comment] 2021-01-05 05:06
@mchamberland are you alright for me to close this issue?

**Comment by mchamberland** [comment] 2021-01-05 11:09
@mchamberland yep. I’m watching the other two repos where this is being worked on.

**Closed** 2021-01-05 12:08 UTC
