### ISSUE TITLE
Create a top-level PyMedPhys paper

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1562] opened 2021-10-26 20:35 UTC
Heya @Matthew-Jennings, @sjswerdloff, and @pchlap,

There was a recent request on how to cite PyMedPhys: 

https://pymedphys.discourse.group/t/how-to-cite-pymedphys-repository/188/2?u=simonbiggs

When looking at the current citations they certainly are growing:

https://scholar.google.com/scholar?q=pymedphys

Someone's even using my electron factors code :slightly_smiling_face: (https://aapm.onlinelibrary.wiley.com/doi/full/10.1002/acm2.13430).

We do need to set up a PyMedPhys top-level paper. There can be room for other papers down the line that focus on a specific module, but for now, we do really need a project paper. Is there a volunteer from among us maintainers to spearhead the writing of said paper?

Or potentially one of our recently active contributors might want to spear-head it? @rembishj or @dg1an3?

---

I would suspect that anyone who meets the following criteria would be included as an author:

* Has made contributions to PyMedPhys and at some point been active within the GitHub repo
* Contributes to the writing of the paper

**Comment by sjswerdloff** [comment] 2021-10-30 01:16
> > focus on the stuff that people want to cite might be best).
> 
> One of my thoughts was that potentially we could have the paper primarily focus on it providing a means for Medical Physicists to write code together, and then give a few examples... but not to have the examples be the paper itself. Down the line one of those examples could be its own paper I guess?
> 
> I'm not sure... the idea is a bit fuzzy...
> 
> Keen for you to take in the direction that you believe fits best. (So don't give to much weight to my fuzzy idea)

While I need to figure out the wording, the real starting place as far as I can tell is that it was intended as a means of clinical medical physicists to share tools for accomplishing regular tasks that were not addressed by the vendors, or for which the tools were particularly expensive.  However, research often involves improving on how "regular
" tasks are performed, or those regular tasks are a part of an overall process on which research is taking place, and that is how we find ourselves with people using PyMedPhys to. aid them in their research.
And then we list a handful of those research papers or projects.  Perhaps explain "what" the particular part of the library is in use and the general medical physics aspect of it (not "how this works" but "why it is needed").

**Comment by SimonBiggs** [comment] 2021-10-30 01:20
> not "how this works" but "why it is needed"

Yup, sounds like a great approach.

> And then we list a handful of those research papers or projects.

:+1:

**Comment by rembishj** [comment] 2021-11-10 18:59
I apologize for being late to the party, but I'm more than happy to join in writing the paper! 

@sjswerdloff Have you begun writing anything yet?

**Comment by SimonBiggs** [comment] 2021-11-10 20:36
Awesome :) thanks @rembishj

**Comment by sjswerdloff** [comment] 2021-11-11 00:56
> I apologize for being late to the party, but I'm more than happy to join in writing the paper!
> 
> @sjswerdloff Have you begun writing anything yet?

Hi @rembishj , no I have not.  If you want to pick this up, by all means.  I took a look at some of the papers (joss.theoj.org) and some discussion right here, but that is as far as I've gotten so far.

**Comment by SimonBiggs** [comment] 2021-11-11 01:32
Hi @rembishj,

Here are details of what a joss paper should contain:

https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

If you just wanted to make a "paper" directory within the repo and start writing a markdown file of a similar format to the following:

https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by SimonBiggs** [comment] 2022-01-13 00:15
Things that should be included are:

* What it's being cited for -- https://scholar.google.com.au/scholar?start=0&q=pymedphys&hl=en&as_sdt=0,5
* What is exposed in the documentation -- https://docs.pymedphys.com/
* What people are trying/using in their clinic as per the discourse group -- https://pymedphys.discourse.group/
* What is still being used at RCCC/NBCC even after I have left
  * Examples -- https://www.youtube.com/watch?v=_HeJBfkXfxg
  * @JacobMcAloney can you comment on everything in PyMedPhys you still use regularly just to have an idea on what should be included in a paper?

**Comment by JacobMcAloney** [comment] 2022-01-13 04:44
@SimonBiggs, things we still use regularly (and are still working somehow 8 months after you left):

- WL arc (including "daily" iteration)
- Metersetmap comparison
- CT extend
- Electron insert factor modelling
- Monaco archive tool

**Comment by SimonBiggs** [comment] 2022-01-13 04:55
> CT extend

Heads up, a Streamlit update removed some of the things needed for CT extend... so at some point in the future a PyMedPhys update will likely break that app

**Comment by SimonBiggs** [comment] 2022-01-13 04:58
Also, is there interest from you and/or @msobolewski in being involved in the paper writing?

**Comment by JacobMcAloney** [comment] 2022-01-13 05:10
Can't comment for Matt of course, but I'm certainly interested to help as I can

**Comment by SimonBiggs** [comment] 2022-02-08 20:37
Hi @Matthew-Jennings,

Might you be in a position to take a leading role in making this paper happen?

**Comment by rembishj** [comment] 2022-02-10 18:47
@SimonBiggs Sorry I'm just getting back to this. I'm working on this now, and it can be found in the joss-paper branch.

Everyone please feel free to hop in and make changes as needed.

**Comment by SimonBiggs** [comment] 2022-02-10 21:25
No stress @rembishj :) thanks for jumping in :)

**Comment by rembishj** [comment] 2022-03-15 15:52
@SimonBiggs could you take a look at this and let me know what you think? Right now it is very short, and I'm not sure what else (if anything) I should add to it. Thanks!

**Comment by SimonBiggs** [comment] 2022-03-15 19:37
Hi Jake :),

I'm currently traveling. Would you be able to provide a direct link to the document so that I can quickly find it and have a read through?

**Comment by SimonBiggs** [comment] 2022-03-18 22:49
Hi @rembishj,

Thanks for sending through the paper draft:

[popx37dvheex0chvtefo.pdf](https://github.com/pymedphys/pymedphys/files/8308003/popx37dvheex0chvtefo.pdf)

I think it is the right level of brevity and conciseness that JOSS reviewers are looking for.

I'm going to move this conversation over to [the pull request](https://github.com/pymedphys/pymedphys/pull/1622) where I will ping the current authors, but I'll also ping historical contributors to PyMedPhys to see if they'd be interested in being involved in the authorship of this paper.

Cheers,
Simon

**Closed** 2022-06-10 19:31 UTC
